# version: '3.8'

services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   networks:
  #     - kafka-net


  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    # image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      # - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
    volumes:
      - ./topics-init.sh:/topics-init.sh
    # user: root
    entrypoint: ["/bin/bash", "-c", "chmod +x /topics-init.sh && /etc/confluent/docker/run && sleep 50 && bash /topics-init.sh"]
    networks:
      - kafka-net

  redpanda-console:
    image: docker.redpanda.com/vectorized/console:latest
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: "kafka:9092"
    depends_on:
      - kafka
    networks:
      - kafka-net

  # kafkaui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: "local"
  #     KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka:9092"
  #   depends_on:
  #     - kafka
  #   networks:
  #     - kafka-net

  # akhq:
  #   image: tchiotludo/akhq
  #   container_name: akhq
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     AKHQ_CONFIGURATION: |
  #       akhq:
  #         connections:
  #           local:
  #             bootstrap.servers: "kafka:9092"
  #   depends_on:
  #     - kafka
  #   networks:
  #     - kafka-net

networks:
  kafka-net:
    driver: bridge
